[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "frontend/dist"

# Ensure React Router works on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


